name: Build C# Application

on:
 name: Build C# Application

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Укажите версию .NET, соответствующую вашему проекту

      - name: Restore dependencies
        run: dotnet restore byky_korowa/byky_korowa.csproj

      - name: Build application
        run: msbuild byky_korowa/byky_korowa.csproj /p:Configuration=Release /p:OutputPath=./build

      - name: Publish application
        run: msbuild byky_korowa/byky_korowa.csproj /p:Configuration=Release /p:PublishProfile=FolderProfile /p:OutputPath=./publish

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: byky_korowa_v1_exe
          path: ./publish

