name: Build C# Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3

      - name: Restore dependencies
        run: nuget restore byky_korowa.sln

      - name: Build project
        run: msbuild byky_korowa/byky_korowa.csproj /p:Configuration=Release /p:Platform="Any CPU"

      - name: Publish project
        run: msbuild byky_korowa/byky_korowa.csproj /p:Configuration=Release /p:Platform="Any CPU" /p:OutputPath=output

      - name: Copy EXE to output
        run: copy byky_korowa\bin\Release\*.exe output\

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: byky_korowy_v1-exe
          path: output/*.exe
